read_holding_registers:
  name: Read Holding Registers (Modbus Function Code 3)
  fields:
    device:
      name: Device
      example: "Inverter"
      required: true
      selector:
        device:
          filter:
            - integration: solarman
    address:
      name: Address
      example: 16384
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    count:
      name: Count
      default: 1
      required: true
      selector:
        number:
          min: 1
          max: 125
          mode: box

read_input_registers:
  name: Read Input Registers (Modbus Function Code 4)
  fields:
    device:
      name: Device
      example: "Inverter"
      required: true
      selector:
        device:
          filter:
            - integration: solarman
    address:
      name: Address
      example: 16384
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    count:
      name: Count
      default: 1
      required: true
      selector:
        number:
          min: 1
          max: 125
          mode: box

write_single_register:
  name: Write Single Register (Modbus Function Code 6)
  fields:
    device:
      name: Device
      example: "Inverter"
      required: true
      selector:
        device:
          filter:
            - integration: solarman
    address:
      name: Address
      example: 16384
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    value:
      name: Value
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box

write_multiple_registers:
  name: Write Multiple Registers (Modbus Function Code 16)
  fields:
    device:
      name: Device
      example: "Inverter"
      required: true
      selector:
        device:
          filter:
            - integration: solarman
    address:
      name: Address
      example: 16384
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
    values:
      name: Values
      example: |
        - 1
        - 2
        - 3
      required: true
      selector:
        number:
          min: 0
          max: 65535
          mode: box
